### PR TITLE
add all rulebook monsters

### PR DESCRIPTION
**Pull request by chrpow**
Adds all monsters from the core rulebook to the system compendium. Uses existing monsters' IDs when possible.

### CODE REVIEW

**Comment by chrpow** [comment]
For #690

**Comment by Muttley** [comment]
There seems to be a mix of items/actors in the compendium now (NPC Attacks, NPC Features and NPC Spells to name a few).  I'd prefer it if we split those out into their own compendiums to keep things organised.

**Comment by PrototypeESBU** [comment]
@Muttley correct me if I'm wrong, but it seems like all those items get built into the monster actor?. The source is split, but those don't get created as sperate items in the compendium. I don't see any value in creating them as independent items, there's almost not overlap between features and attacks between monsters.

**Comment by chrpow** [comment]
> One thing I thought of is that we should get the updated stat block formatting onto these monsters. @chrpow are you able to pull down this branch: 697-improve-monster-importer and update using the new changes?

I'm trying this now. What should be different using the improved importer? Is there a particular monster or feature I can check for to verify that everything worked?

**Comment by PrototypeESBU** [comment]
The stat block in the monster description should now have the correct values in bold. if you looks at your changes to Acolyte for instance, you'll see that the new version in this PR removed the <strong> tags. Maybe we should close this PR and wait for these changes in 1.8.0 first,

**Comment by chrpow** [comment]
Will close this PR. I've sent @PrototypeESBU the compendium files to review offline.

**Pull request closed without merging**
