### PR TITLE
New Feature: Monster Importer

### PR DESCRIPTION
**Pull request by PrototypeESBU**
I wanted to learn more about foundry development and give back to this project at the same time. I present for consideration, the Monster Importer! 
image

**Usage:** 
Copy and paste a monster stat block to automatically add that monster as an NPC.

**Testing:** 
Tested against almost all monsters in the core rules. Limited testing with 3rd party content, but generally no issues. 
No automated test cases created. (Would love to learn how to do this.)

### CODE REVIEW

**Comment by Muttley** [comment]
I'll have a look at this, thanks.

One thing I would say is that we probably don't want an Import Monster button on the Actors tab, it would be better just being triggered by a macro as once the GM has imported all the monsters it's just a useless button taking up space.  The character importer on the other hand will always remain useful.

**Comment by PrototypeESBU** [comment]
Currently the button is only visible to GMs. The genesis of the idea was based on the fact that I often found myself implementing monsters on the fly at game time and needed a quicker way to do that. Kind of a low prep gm mentality. I'm not well practiced on modifying the UI so I just copied the other import, but there is there a more streamlined way triggering the popup, I'm all game.

**Comment by Muttley** [comment]
Best thing to do is add a new static method for launching the import tool to the ShadowdarkMacro class (see `system/src/macro.mjs`) and then creating a simple new macro that calls this.  See `data/macros/initialize-luck.mjs` for an example calling one of these static methods.

**Comment by PrototypeESBU** [comment]
I got the macro thing working. Thanks. 
The only thing I don't like about the macro only approach, is that it's very counter intuitive to people not familiar with the ins and outs of Foundry. For the first month of hosting shadowdark, I was hitting F5 every time I needed the light tracker back because I couldn't find a way to bring it back in the interface. 

Would something like this be viable?
image

Also, has there been any thought on how the upcoming character creator would get launched?

Thanks!

**Comment by Muttley** [comment]
> The only thing I don't like about the macro only approach, is that it's very counter intuitive to people not familiar with the ins and outs of Foundry. For the first month of hosting shadowdark, I was hitting F5 every time I needed the light tracker back because I couldn't find a way to bring it back in the interface.

That's more of an education thing to be honest.  We could do with a documentation journal that is auto-imported/displayed on a newly created world.  I can guarantee users wouldn't bloody read it though.  ;)

> Would something like this be viable? image

No, I don't like that at all I'm afraid.

> Also, has there been any thought on how the upcoming character creator would get launched?

For that I'd have it as a button on the Actor tab.  Probably replacing the `Import Shadowdarkling` button which would be relegated to a macro as it's no longer as needed.

**Comment by PrototypeESBU** [comment]
Ok the PR should be ready to ship now with macro only trigger.

> That's more of an education thing to be honest. We could do with a documentation journal that is auto-imported/displayed on a newly created world. I can guarantee users wouldn't bloody read it though. ;)
I agree with you that documentation should get people up to speed with features like this, but I also agree that they will never read it. ha! That's why I would advocate for a UI option for newbie features, but let's table that for now.

> For that I'd have it as a button on the Actor tab. Probably replacing the Import Shadowdarkling button which would be relegated to a macro as it's no longer as needed.
Ah yeah, I figured as much. That makes sense and thanks for the response!

**Comment by PrototypeESBU** [comment]
I think this PR is superseded by #555 now

**Comment by Muttley** [comment]
Added an issue for this.
closes #557

**Pull request merged**
