### PR TITLE
Change clockwise initiative to alphabetical order

### PR DESCRIPTION
**Pull request by chrpow**
This is a change to PR #592

I've modified the clockwise initiative code so that player character tokens are sorted alphabetically rather than based on user configuration.

This also makes the system a bit more robust as it should always put every combatant in the initiative order, even if something is preventing them from rolling. For instance, I tested on a group of combatants with various "problems":
image
In this picture, Aboleth is a regular NPC (rolls normally), Basilisk is an NPC whose actor has been deleted and therefore has no roll data (goes after the other NPCs), Light is a light actor with no roll data (goes at the end of the GM's turn), Elbin is a PC belonging to a logged-in player, and Jorbin is a PC with no attached player.

This way, the behavior of the clockwise initiative tracker more closely replicates the default initiative system, which will roll for all combatants even if their actors don't have roll data. By default, combatants without actors are assigned initiative 0, so in clockwise initiative I just grouped them at the end of the GM's turn.

The only thing remaining before implementing this is to integrate the i18n changes in the *.yaml files into the *.json files, but I'm not sure how to do that.

### CODE REVIEW

**Comment by Muttley** [comment]
> The only thing remaining before implementing this is to integrate the i18n changes in the *.yaml files into the *.json files, but I'm not sure how to do that.

All you need to do for that is add the English translations to en.yaml and Crowdin will take care of the rest once it has been merged and they'll just show up on Crowdin as new translations needed for the other languages and the default English will be added to their specific files.

So, just to clarify, once players/NPCs have rolled, the highest roll goes first and then the rest are looped alphabetically from that position?  For example.

ActorA rolls 7
ActorB rolls 11
ActorC rolls 5

Then the order will be: ActorB, ActorC, ActorA

Is that corrent?

**Comment by chrpow** [comment]
Correct, in that case it would go B, C, A. And if, for example, A represented an NPC, then the order would be B, C, NPC1, NPC2, etc.

**Comment by chrpow** [comment]
I screwed something up with the merge since the changes were spread across two pull requests. I will resubmit this entire change as one PR.

**Comment by chrpow** [comment]
This should be okay to merge now. This includes the changes from both PRs.

**Pull request merged**
