### PR TITLE
670 bracers of defense bug

### PR DESCRIPTION
**Pull request by mrstarbuck007**
### SUMMARY
To solve this, I implemented a system to track which location on the body a wearable item (e.g. Gauntlets of Might) is located: Head, Arms, Hands, Torso, Legs, Feet, Shield, or Cloak.  Non-wearable items (e.g. potions) do not have a body location and cannot be equipped; only wearable items can be equipped.  When an item is equipped, all other items equipped in the same location are automatically unequipped.  Also, unequipping an item disables its related ActiveEffect on its Actor, and equipping it enables it.  

### CHANGES
**Wearable Items' JSON Files**
* Added "system.bodyLocation" field 
* Set "canBeEquipped" = true
* Changed non-AC affecting items to Basic type.  Only AC affecting items are Armor type.
* Changed "disabled" = true for wearable items' active effects, so that they are not applied when the item is added to the inventory unequipped.

**Item Sheet**
* added Body Location dropdown list

**ItemSheetSD**
* added _onBodyLocation() event handler to sync "canBeEquipped" value with body location value

**ActorSD**
* deleted updateArmor() method in ActorSD as obsolete.
* deleted related updateArmor() test
* updated updateArmorClass() method to handle multiple Armors being enabled

**PlayerSheetSD**
* updated _onToggleEquipped() event handler to handle body locations
* added _toggleActiveEffects() method to enable/disable items' related ActiveEffects on their ActorSD

### TESTS
I ran all of the tests in Quench and got the same test failures that occurred on the `develop` branch, so I don't think I broke anything that wasn't already broken.  I haven't added any new unit tests yet, I plan to do so but need to familiarize myself with how to implement them.  But I wanted to get this pull request out there so it could be looked at sooner.

### CODE REVIEW

**Comment by Muttley** [comment]
I'm sorry, but I don't think this is the right approach.  Shadowdark RPG doesn't have any concept of body locations for armor, and I really don't want the system to stray from the core game design principles.

**Comment by Muttley** [comment]
This issue has now been resolved another way in the develop branch

**Comment by mrstarbuck007** [comment]
Point taken regarding the RPG not having body locations; the system shouldn't add restrictions where the RPG has none.  But what about being able to toggle on/off the active effect from an item by equpping/unequipping it?  For example, if I have Gauntlets of Might and (homebrew) Gloves of Dexterity (18 Dex override) in my inventory, currently both active effects will apply even though my DM says I can only use one at a time.  We could mark them "canBeEquipped": true and use the _toggleActiveEffects() method to turn them on/off.  There would still be no restriction on equipping; I could equip both and get both effects if allowed for some reason (maybe a _wish_ gave me an extra pair of arms).  Let me know what you think.

**Comment by Muttley** [comment]
> But what about being able to toggle on/off the active effect from an item by equpping/unequipping it? For example, if I have Gauntlets of Might and (homebrew) Gloves of Dexterity (18 Dex override) in my inventory, currently both active effects will apply even though my DM says I can only use one at a time.

I think we could really need a new tab section on the character sheet for manipulating active effects TBH.  Unfortunately the way Foundry handles those is kinda weird.  I might borrow the code from the Achtung! Cthulhu and Fallout systems I also develop.

The upside is that with the limited inventory slots, players are not likely going to be able to hoard tons of equipment like they do in other games.

**Comment by mrstarbuck007** [comment]
Gotcha.  Well, even though this PR got declined, I learned a lot about the
system while coding it.  I'll take a stab at another issue when I have some
more free time.

**Comment by Muttley** [comment]
> Gotcha. Well, even though this PR got declined, I learned a lot about the system while coding it. I'll take a stab at another issue when I have some more free time.

Learning is always good, and it will also help with any other Foundry systems you may end up tinkering with.

Even though your PR was declined (this time), the effort *was* very much appreciated.

**Pull request closed without merging**
