### PR TITLE
Fixed all Tours and added 1 more

### PR DESCRIPTION
**Pull request by PrototypeESBU**
None of the tours were working. Fixed all 3 of the existing ones and added one more for the Monster Importer.

### CODE REVIEW

**Comment by Muttley** [comment]
Is there an associated ticket for the tours not working?  If not, could you open one so we have a log of it?

**Comment by PrototypeESBU** [comment]
Fixes #556

**Comment by Muttley** [comment]
Could you rebase your fork to the latest commit in the main develop branch and update this pull request?  I'll try and get these fixes out today.

**Comment by PrototypeESBU** [comment]
Looks good now

**Pull request merged**
